### PR TITLE
Add `create_result` and `update_order`

### PR DESCRIPTION
**Pull request by diazruy**
- Now using output directly as generated from OpenAPI generator, with no modifications. This nukes previous manual edits performed to various parts which were dangerous and easy to overlook (most of which were technically unnecessary and have been dealt with in different manners (for example, see [this](https://github.com/PrimaryDotHealth/connect-ruby-client/pull/11#issuecomment-1120066876)). No further manual modifications should be being made to the generated files to prevent this. 
- `scripts/generate_clients.sh` in `connect` [has been replaced](https://github.com/PrimaryDotHealth/connect/pull/425/commits/b960976b4704a7a0cb4730447c2281b6a7d0d23a) by individual rake tasks per language and the Ruby one has been made to consume a version number (e.g. `rake connect_client:ruby[1.0.0]`) that gets piped into the generated client, as well as copying the updated files to the sibling folder containing the gem, ready for publishing.
- Now includes the models generated off of the Swagger schemas, given that the responses to client calls (which [now have explicit schemas](https://github.com/PrimaryDotHealth/connect/pull/149/files#diff-2a9b6c04d7314f0b1bed91e5cf85305c5e5d6e61399e5ed9a1d9900508f9bc42R28-R41) for better documentation) would otherwise be wrapped in `InlineResponse200X` classes which makes for a poor dev UX when using the client. Now the responses are more clearly `PrimaryConnectClient::Orders`, `PrimaryConnectClient::OrderIds`, etc.
- Adds the new `update_order` and the previously undocumented `create_result` API endpoints

### CODE REVIEW

**Review by shawnd — APPROVED** [review]

**Comment by shawnd** [comment]
Check if manual edits here need to be carried over:
https://github.com/PrimaryDotHealth/connect-ruby-client/pull/11/files?diff=split&w=0#diff-b97af097a57a828723b654c6e2769dab866159b5d2ddce9ed1b46fc9b881334eL145-L198

**Review by DamonGroove — APPROVED** [review]
lgtm

**Comment by diazruy** [comment]
@shawnd 

> Check if manual edits here need to be carried over: [#11 (files)](https://github.com/PrimaryDotHealth/connect-ruby-client/pull/11/files?diff=split&w=0#diff-b97af097a57a828723b654c6e2769dab866159b5d2ddce9ed1b46fc9b881334eL145-L198)

So I followed the rabbit hole, and turns out that OpenAPI [doesn't have a "good" way to handle redirect responses](https://github.com/OAI/OpenAPI-Specification/issues/2512). The only suggestion I found was [this one](https://stackoverflow.com/a/70463412), which suggests indicating that the response has a `Location` header, which I did by adding
```ruby
      response(302, 'found') do
        header 'Location', schema:  { type: :string }, description: 'The signed URL to download the report'
```
which correctly adds the documentation like this

image

**IMPORTANT**: `rswag` docs indicate that the `header` should be specified like
```ruby
        header 'Location', type: :string, description: 'The signed URL to download the report'
```
(without the `schema:`), but this actually causes OpenAPI generator to choke on it given that the generated YML ends up like

```yml
      responses:
        '302':
          description: found
          headers:
            location:
              type: string
              description: The signed URL to download the report
```
instead of 
```diff
      responses:
        '302':
          description: found
          headers:
            location:
-              schema:
-                type: string
+              type: string
              description: The signed URL to download the report
```
which is actually [what the Swagger docs](https://swagger.io/docs/specification/describing-responses/#headers) indicate it should be.

That all said, even with these changes, the generated `get_lab_report` method on the client _still_ returns `nil`, which is what I think @samsohn28 was trying to get around. I think what needs to happen is that when we want access to the response headers, we need to call `get_lab_report_with_http_info` instead of `get_lab_report` (which uses `get_lab_report_with_http_info` internally and returns the `data` exclusively), which [returns not just the `data` (which is useless in our case) but also the `status_code`, and (more importantly) the `headers`](https://github.com/PrimaryDotHealth/connect-ruby-client/pull/11/files#diff-b97af097a57a828723b654c6e2769dab866159b5d2ddce9ed1b46fc9b881334eR202), which can then be used to follow the redirect. 

Interestingly enough, looks like `health` is [not  even actually yet using the `get_lab_report` endpoint](https://github.com/PrimaryDotHealth/health/blob/master/app/jobs/communication_task/pull_from_connect.rb/#L162) anyway.

**Review by samsohn28 — APPROVED** [review]
Awesome, thanks for handling the manual edits I made!

**Pull request merged**
